import { services } from '@/features/services/services';
import { StructuredData } from '@/components/seo/StructuredData';
import { pageMetadata, personSchema, websiteSchema, webPageSchema, breadcrumbs } from '@/lib/seo';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { SiteHeader } from '@/components/layout/SiteHeader';
import { SiteFooter } from '@/components/layout/SiteFooter';
import { SectionNavigator } from '@/components/navigation/SectionNavigator';
import { ServiceCards } from '@/features/services/ServiceCards';
import { ToolsOrbit } from '@/features/services/ToolsOrbit';
import styles from '@/features/services/Services.module.css';
export const metadata = pageMetadata('/services', "Website, Web & Mobile App Development Services", "Business websites, web and mobile apps, marketplaces, fintech interfaces and courier tracking systems. Discuss your project with Dennis Okaro Jones.", 'services');
export default function ServicesPage() {
  return <><StructuredData data={{ '@context': 'https://schema.org', '@graph': [personSchema, websiteSchema, webPageSchema('/services', 'Website, Web & Mobile App Development Services', 'WebPage'), breadcrumbs('/services', 'Services'), { '@type': 'OfferCatalog', '@id': 'https://dennis.rcentz.cc/services#catalogue', name: 'Website and application development services', itemListElement: services.map(service => ({ '@type': 'Offer', itemOffered: { '@type': 'Service', name: service.title, description: service.description, provider: { '@id': personSchema['@id'] }, url: 'https://dennis.rcentz.cc/services' } })) }] }} /><SiteHeader /><main id="main-content" tabIndex={-1} className={styles.page}><section className={styles.section} aria-labelledby="services-title"><div className={styles.container}>
    <div className={styles.heroLayout}><header className={styles.heading}><p className={styles.eyebrow}>Services / Websites & applications</p><h1 id="services-title" className={styles.title}>From your next idea<br /><span className="gradient-text">to a working product.</span></h1><p className={styles.description}>Websites and applications for businesses of different sizes and sectors. Whether you need a clear online presence, a mobile app or a connected business system, let’s define what your product needs to do.</p><div className={styles.actions}><Link href="/contact" className={styles.button}>Discuss your project <ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/projects" className={styles.button}>See my work</Link></div></header><ToolsOrbit /></div>
    <section aria-labelledby="service-catalogue-heading"><header className={styles.catalogueHeading}><p className={styles.eyebrow}>Development services</p><h2 id="service-catalogue-heading">Choose what your business needs next.</h2><p className={styles.description}>From a focused website to a connected application, each project starts with a clear purpose and an agreed scope.</p></header><ServiceCards /></section>
    <section className={styles.proofSection} aria-labelledby="service-proof-heading"><div><p className={styles.eyebrow}>Work behind the services</p><h2 id="service-proof-heading">See the systems<br /><span className="gradient-text">behind the promise.</span></h2><p className={styles.description}>Explore independent products and contributions to existing platforms, with live demos, repositories and a clear description of my role.</p><Link href="/projects" className={styles.cardLink}>View full portfolio <ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className={styles.proofLinks}><Link href="/projects#waffi">Waffi Market<span>Multi-vendor commerce</span></Link><Link href="/projects#jobrcentz">JobRcentz<span>Jobs, applications and interview workflows</span></Link><Link href="/projects#fintech">Multi-asset fintech<span>Contributions to an existing financial platform</span></Link></div></section>
    <section className={styles.process} aria-labelledby="process-title"><p className={styles.eyebrow}>How we work</p><h2 id="process-title" className="mt-3 text-2xl font-bold">A clear path from brief to delivery.</h2><div className={styles.steps}>{[
      ['01 / Understand', 'We discuss your users, business goals and the features that matter.'],
      ['02 / Define & build', 'We agree the scope and develop the interface, data and workflows around it.'],
      ['03 / Review & launch', 'We review the result, validate the agreed features and plan deployment and ongoing support.']
    ].map(([title, description]) => <div key={title}><h3>{title}</h3><p className={styles.description}>{description}</p></div>)}</div><div className={styles.actions}><Link href="/contact" className={styles.button}>Tell me what you need <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
    <section className={styles.scopeSection} aria-labelledby="scope-heading"><p className={styles.eyebrow}>Planning your project</p><h2 id="scope-heading">Bring the idea. Let’s define the details.</h2><div className={styles.steps}><div><h3>Your brief</h3><p className={styles.description}>Tell me who will use the product, the problem it solves, the features you need and your preferred timeline.</p></div><div><h3>Your delivery scope</h3><p className={styles.description}>We agree the screens, workflows, integrations, review stages and deployment requirements before development.</p></div><div><h3>Your next steps</h3><p className={styles.description}>Ongoing support, maintenance and future improvements are discussed around the needs of your product.</p></div></div><div className={styles.actions}><Link href="/contact" className={styles.button}>Start a project conversation <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
    <section className={styles.scopeSection} aria-labelledby="coverage-services-heading"><p className={styles.eyebrow}>Local &amp; remote collaboration</p><h2 id="coverage-services-heading">Build from wherever your business works.</h2><p className={styles.description}>Based in Warri, Delta State, I welcome projects from businesses in Lagos and across Nigeria, and remote enquiries from international teams. Explore the working process and share your brief.</p><div className={styles.actions}><Link href="/website-development" className={styles.button}>Website development in Nigeria <ArrowUpRight size={16} aria-hidden="true" /></Link><Link href="/remote-website-development" className={styles.button}>Remote website development <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
  </div></section></main><SiteFooter /><SectionNavigator showMarkers={false} /></>;
}
